# Generated by Django 2.2.28 on 2025-02-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qustions',
            new_name='Questions',
        ),
    ]
